name: "Deploy to AWS"

on:
  workflow_dispatch:

jobs:
  Deploy_to_AWS:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install dependencies"
        run: npm install

      - name: "Install pm2 globally"
        run: npm install pm2 -g

      - name: "Run the tests"
        run: npm test

      - name: "Deploy to AWS"
        run: pm2 start server.js
